### ISSUE TITLE
tableau de données

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/ESI_viande_brousse#11]
dans le tableau de données, en dessous du graphique il y a de la place, ce serait bien de mettre une colonne "scientific name" en plus du nom français histoire que des personnes non francophone s'y retrouve.

**Comment by VincentBlase** [comment]
Je l'ai rajouté dans le tableau

**Comment by yannickkk** [comment]
ok tu n'as pas fait la colonne que j'avais demandé mais bon j'achète
