### ISSUE TITLE
correction sur ui et server

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/ESI_viande_brousse#15]
Salut Vincent, j'ai regarder, c'est super, on va faire quelques modif de forme:

ligne10 "Choose species" remplacé par "Choice species"
Il faut donner plus de place au graphique:
ligne 15 ajouter width = 2
ligne 20 ajouter width = 10
Si tu trouves comment lui donner plus de place en hauteur ce serait super car il est un peut trop tassé encore.
UI ET SERVER
"Tous les marchés" remplacé par "whole markets"
"Toutes les espèces" remplacé par "whole taxa"
"Nom latin" remplacé par "Scientific name"
server
ligne 61
data_cut$ESPECE.OBSERVEE remplacé par tolower(data_cut$ESPECE.OBSERVEE)

axe des x remplacer "espèces" par "species"
axe y "Fréquences cumulées" par "meat occurrences"
axe y "Fréquences (occurances/nbre visites) cumulées" par "meat occurrences/nber of visits"
lorsque le log est coché "log(meat occurrences)" ou "log(meat occurrences/nber of visits)"

**Comment by VincentBlase** [comment]
J'ai tout corrigé ! Et j'ai reussi à régler la hauteur aussi

**Comment by yannickkk** [comment]
dans l'onglet d'affichage du wikki espece, c'est décalé sur la droite car dans mon script j'avais width = 2 pour la barre de sélection fais de même et fait le lien vers les données de l'iucn (nouvelle page) voir le script que je t'ai envoyé. Avec ce que tu as fait toi on quitte la page de l'app et je en veux pas de ça !! d'autre part essaye de rendre "more informations" plus visible en grossissant un peut la police et en alongeant el text "More informations about this species ......"

   observeEvent(input$species,{
     specie <- as.character(input$species)
    if (specie != "") {browseURL(as.character(unique(data[which(data[,"species"]== specie),"URL"])))}
   })

merci

**Comment by VincentBlase** [comment]
Tout est corrigé

**Comment by yannickkk** [comment]
ok j'achète bravo
