### ISSUE TITLE
il y a encore une coquille dans le fichier de données

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/ESI_viande_brousse#16]
data_final à encore des signes cabalistiques à  la place des accent, c'est du à un passage en utf-8 j'ai vu protégé écrit prot<e9>g<e9> par exemple à voir si il n'y en a pas d'autre et les corriger lors du chargement.
Fum<e9>s
prot<e9>g<e9>
kaKakamo<e9>ka

**Comment by VincentBlase** [comment]
C'est corrigé normalement
