### ISSUE TITLE
fichier de nettoyage

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/ESI_viande_brousse#18]
Vincent,
Pourrais tu stp refaire ton export 2019.csv en csv2 cad un csv avec comme séparateur ";". Tous les autres csv sont exporter comme cela (et chez moi j'ai aussi exporté 2019 en csv2).
Du coup dans ton script il faudra modifier
data_2019 <- read.csv(file = '2019.csv',header=TRUE, encoding = 'UTF-8')
par 
data_2019 <- read.csv2(file = '2019.csv',header=TRUE, encoding = 'UTF-8')
L'export de fichier francophones en csv2 est moins dangereux qu'un export en csv car csv utilise la , comme séparateur de colonne et les français la , comme séparateur de décimale. Le csv2 utilise le ; comme séparateur de colonne ce qui n'interfère pas avec notre séparateur de décimale ",".
merci

**Comment by VincentBlase** [comment]
En effet mon export n'était pas adapté, j'ai corrigé !
