### ISSUE TITLE
Fichier data_final modifié à la main ??

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/ESI_viande_brousse#19]
J'ai après quelques galère j'ai relancé l'App.
Ma galère venait du fait que tu as modifié NOM LATIN dans data_final par Scientific_name.
Ce n'est pas un problème en soit (d'ailleurs on pourrait renommer tous les noms de colonnes du fichier qui sont pourris, j'ai rien contre pour les passer en minuscule et enlever les . mais il faut l'écrire dans le script). Là visiblement tu l'as fait à la main et c'est mal.
J'ai d'abord essayé de lancer l'appli ça planté. Je me suis donc dis que tu avais changer le fichier d'entrée et comme tu m'avais renvoyé les scripts j'ai tout fait retourner.
Finalement ça planté toujours et j'ai fini par comprendre que ça venait de l'ui et j'ai trouvé ce changement de nom de colonne qui en est la cause.
Le code doit être répétable, il faut donc que tu inscrive ce changement de nom dedans.

**Comment by VincentBlase** [comment]
Je ne comprends pas, j'ai bien modifié dans l'UI "NOM.LATIN" par "Scientific_name" pour qu'il n'y ait pas d'erreur et ça fonctionne chez moi.
J'ai effectué le changement de nom dans le 3_add_taxonomy_to_data et est donc répétable ?

**Comment by yannickkk** [comment]
voir les deux fichiers que je t'ai envoyé pour avoir le statut l'UICN à jour dans el fichier data_final, ce statut évolue au fil des années et je ne suis pas certain que celui qui est dans le fichier source soit à jour. Avec ses script on le réccupère sur site de l'iucn c'est plus propre.
