### ISSUE TITLE
c'est parti.... passer le chargement des packages dans le fichier global.R

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/ESI_viande_brousse#2]
Tu m'avais envoyé le code dans un seul fichier je voulais donc te suggérer de séparer le code, ce que tu as fait maintenant, c'est bien.
Tu as chargé les packages dans les deux scripts ui.R et server.R tu peux les mettre dans l'un ou l'autre mais les mettre dans les deux ne sert à rien. 
D'autre part il y a un fichier qui s'appelle global.R que j'ai créé, ce fichier est reconnu par l'app sans être appelé, il permet de lancer des commandes et créer des objets une seule fois en début de session. Il constitue la partie non réactive de l'application (celle avec laquelle l'utilisateur n'interagit pas).

**Comment by VincentBlase** [comment]
Vu

**Comment by yannickkk** [comment]
Les packages à charger peuvent être mis dans global ça évite de les avoir tout le temps sous les yeux dans server

**Comment by yannickkk** [comment]
En fait il faut mettre le chargement des packages dans global ce n'est optionnel si tu ne le fais pas et que tu lances l'appli avec l'UI ouvert sur R studio tu chopes un message d'erreur. Si tu le place dans global l'appli se lance quelque soit le fichier sur lequel tu es.

**Comment by VincentBlase** [comment]
Très bien ! Je vais faire ça

**Comment by yannickkk** [comment]
pas fait !!
