### ISSUE TITLE
inclure le logo d'ESI dans le header

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/ESI_viande_brousse#21]
créer un dossier www dans l'appli y placer le fichier esi.gif (je te l'envoie par mail) et au début de l'ui mettre
ui <- navbarPage(windowTitle = "ESI Pointe Noire bushmeat survey", title=div(tags$a(img(src="esi.gif", style="margin-top: -15px",height ="50" ,width ="179" ), href="https://www.facebook.com/esicongo")),

N.B. dans ce dossier tu pourras aussi mette proto.html et logo_ESI.jpg que je t'ai envoyés tout à l'heure, refaire le path dans proto.html pour trouver logo_ESI.jpg et la page protocole devrait être faite.
@+

**Comment by VincentBlase** [comment]
C'est fait !

**Comment by yannickkk** [comment]
ouvrir la page fb dans une nouvelle fenêtre (voir le script que je t'ai envoyé pour l'iucn)

**Comment by VincentBlase** [comment]
C'est corrigé !

**Comment by yannickkk** [comment]
ok super je ferme
