### ISSUE TITLE
maj du statut iucn dans les fihciers 3 et 4 du script de nettoyage

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/ESI_viande_brousse#24]
voir les deux fichiers que je t'ai envoyé pour avoir le statut l'UICN à jour dans el fichier data_final, ce statut évolue au fil des années et je ne suis pas certain que celui qui est dans le fichier source soit à jour. Avec ses script on le réccupère sur site de l'iucn c'est plus propre. Mail 05052020 8h29

**Comment by VincentBlase** [comment]
Je crois que je n'ai pas reçu ces deux fichiers.
Je n'ai aucun mail à cette date et heure

**Comment by yannickkk** [comment]
renvoyés à 11h07
