### ISSUE TITLE
controle d'accès

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/ESI_viande_brousse#25]
c'est classe ce controle d'accès et el téléchargement j'aime beaucoup.
Par contre quand je télécharge un fichier il se passe rien  : ((

**Comment by VincentBlase** [comment]
Oui c'est normal pour le moment. 
Est-ce qu'il y a moyen d'avoir un peu plus de précision sur ce qui est attendu ici ? Qu'est-ce que l'utilisateur voit et quelle fonctionnalité doit-il avoir accès quand il est connecté ? Qu'est ce qu'il se passe lorsqu'il upload un fichier ?

**Comment by yannickkk** [comment]
ce qui est attendu c'est que le fichier soir téléchargé et que si il existe déjà il soit remplacé.
Comme tu as fait c'est bien il faudrait un truc du style:
download dataset as data_final.csv
download protocole as protocole.html
download account as account.csv
et tu expliques quels sont les nom de champ des fichier csv par exemple:
noms de colonnes pour le fichier account.csv: login;pasword

**Comment by VincentBlase** [comment]
Bonjour !

J'ai réussi à faire en sorte que le fichier data soit remplacé par le nouveau fichier upload.
Cependant, je n'arrive pas à faire en sorte que cela soit fait définitivement : actuellement lorsque l'utilisateur quitte sa session, le fichier qu'il a upload n'est plus pris en compte et le fichier initial est réutilisé.

Je me demande si c'est réellement possible de mettre à jour les données de cette manière ? Est-ce qu'il ne faut pas directement mettre à jour les données côté serveur ? Et un utilisateur ne peut donc pas les mettre à jour lui même ?

C'est du coup le même problème pour le protocole, étant donné que ça veut mettre à jour le .html récupéré dans le serveur, je ne pense pas qu'on peut le mettre à jour côté client. En tout cas pas de manière définitive.

**Comment by yannickkk** [comment]
je regarde ça.
