### ISSUE TITLE
templates

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/ESI_viande_brousse#26]
Es tu certain qu'en appelant le protocole avec le chemin que tu as mis dans l'ui cela marche lorsque l'app sera déployé ?

**Comment by VincentBlase** [comment]
Normalement oui

**Comment by yannickkk** [comment]
cela m'étonnes car c'est un chemin en dur. On verra

**Comment by VincentBlase** [comment]
Je n'avais pas compris le problème au début, j'ai confondu avec autre chose. Je viens de comprendre, en effet je ne sais pas si ça va fonctionner du coup... J'ai essayé de résoudre le problème mais  je n'ai pas trouvé de solution pour le moment, je continue à chercher

**Comment by yannickkk** [comment]
aç devrait marcher
