### ISSUE TITLE
rendre le code lisible

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/ESI_viande_brousse#3]
tu peux (tu dois) structurer ton code. Deux méthodes mais il y en a d'autre.
les indentations, tu peux replier ou déplier des parties de code ex.
#############affichage graphe barplot###########
some code...
##########################################
tu peux créer des modules de programmation et gérer des variables locales, ses modules sont des fichiers qui seront appelés depuis la partie server de l'App généralement avec la fonction source()

**Comment by VincentBlase** [comment]
Très bien ! Merci
