### ISSUE TITLE
Ne charger que les packages essentiel au fonctionnement de l'App

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/ESI_viande_brousse#4]
On a tendance à ouvrir pleins de librairies pour essayer des fonctions super géniales et puis finalement on fait autrement et la librairie ne sert à rien. Quand il faut déployer l'appli ça devient le souk on sait plus si le code l'utilise ou pas !!! alors autant commenter de suite un package qu'on utilise pas ça évite d'en avoir plein à gérer ensuite

**Comment by VincentBlase** [comment]
En effet, merci !
