### ISSUE TITLE
script de nettoyage_ encoding

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/ESI_viande_brousse#6]
data<- read.csv2("data_total.csv", header = TRUE, encoding = "UTF-8")

Si tu as des caractères étranges quand tu ouvres un fichier c'est que l'encoding n'est pas le bon.
Sais tu comment faire pour savoir quel est l'encodage ?
tu devrais ça t'évitera d'avoir à écrire:
#Traitement d'une erreur de chargement sur les "é"
data$LIEU <- str_replace(data$LIEU,"<e9>","e")
data$LIEU <- as.factor(data$LIEU)
data$FORMAT.VENTE <- str_replace(data$FORMAT.VENTE,"<e9>","e")
data$FORMAT.VENTE <- as.factor(data$FORMAT.VENTE)
data$ESPECE.OBSERVEE <- str_replace(data$ESPECE.OBSERVEE,"<e9>","e")
data$ESPECE.OBSERVEE <- as.factor(data$ESPECE.OBSERVEE)
data$STATUT.DE.PROTECTION <- str_replace(data$STATUT.DE.PROTECTION,"<e9>","e")
data$STATUT.DE.PROTECTION <- as.factor(data$STATUT.DE.PROTECTION)
data$NOM.LATIN <- str_replace(data$NOM.LATIN,"<e9>","e")
data$NOM.LATIN <- as.factor(data$NOM.LATIN)
data$STATUT.CONGO <- str_replace(data$STATUT.CONGO,"<e9>","e")
data$STATUT.CONGO <- as.factor(data$STATUT.CONGO)
data$STATUT.UICN <- str_replace(data$STATUT.UICN,"<e9>","e")
data$STATUT.UICN <- as.factor(data$STATUT.UICN)
data$ORIGINE.1 <- str_replace(data$ORIGINE.1,"<e9>","e")
data$ORIGINE.1 <- as.factor(data$ORIGINE.1)
data$ORIGINE.2 <- str_replace(data$ORIGINE.2,"<e9>","e")
data$ORIGINE.2 <- as.factor(data$ORIGINE.2)
data$ORIGINE.3 <- str_replace(data$ORIGINE.3,"<e9>","e")
data$ORIGINE.3 <- as.factor(data$ORIGINE.3)
data$ORIGINE.4 <- str_replace(data$ORIGINE.4,"<e9>","e")
data$ORIGINE.4 <- as.factor(data$ORIGINE.4)
data$DISTRICT.1 <- str_replace(data$DISTRICT.1,"<e9>","e")
data$DISTRICT.1 <- as.factor(data$DISTRICT.1)
data$DISTRICT.2 <- str_replace(data$DISTRICT.2,"<e9>","e")
data$DISTRICT.2 <- as.factor(data$DISTRICT.2)
data$DISTRICT.3 <- str_replace(data$DISTRICT.3,"<e9>","e")
data$DISTRICT.3 <- as.factor(data$DISTRICT.3)
data$DISTRICT.5 <- str_replace(data$DISTRICT.5,"<e9>","e")
data$DISTRICT.5 <- as.factor(data$DISTRICT.5)
data$DISTRICTS <- str_replace(data$DISTRICTS,"<e9>","e")
data$DISTRICTS <- as.factor(data$DISTRICTS)
data$ENTIER...MORCEAUX <- str_replace(data$ENTIER...MORCEAUX,"<e9>","e")
data$ENTIER...MORCEAUX <- as.factor(data$ENTIER...MORCEAUX)
data$REGION <- str_replace(data$REGION,"<e9>","e")
data$REGION <- as.factor(data$REGION)
data$ville.ou.village <- str_replace(data$ville.ou.village,"<e9>","e")
data$ville.ou.village <- as.factor(data$ville.ou.village)
data$ACHETEUR <- str_replace(data$ACHETEUR,"<e9>","e")
data$ACHETEUR <- as.factor(data$ACHETEUR)
data$REMARQUE <- str_replace(data$REMARQUE,"<e9>","e")
data$REMARQUE <- as.factor(data$REMARQUE)
data$FUMES...FRAIS <- str_replace(data$FUMES...FRAIS,"<e9>","e")
data$FUMES...FRAIS <- as.factor(data$FUMES...FRAIS)

**Comment by VincentBlase** [comment]
Si j'ai bien compris, pour connaitre l'encoding, il faut ouvrir le .csv directement et regarder les données brutes non ?
J'ai essayé plusieurs encoding différent (UTF-8, Latin-1 ..etc) mais aucun n'a corrigé ce problème, j'ai donc décidé de le corriger manuellement.

**Comment by yannickkk** [comment]
ouvrir avec notpad++ et regarder l'encoding permet d'ouvrir le fichier avec le bon encoding essayes ça:

data<- read.csv2("data_total.csv", header = TRUE, encoding = "ENSI")
