### ISSUE TITLE
utilisaton de l'arborescence

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/ESI_viande_brousse#8]
En toute logique ton script de nettoyage devrait aller chercher les données dans données brutes
C:/Users/Utilisateur/Desktop/Stage/DonneesBrutes
Et devrait créer le fichier data_nettoyage dans données travaillées
C:/Users/Utilisateur/Desktop/Stage/DonneesTravaillees

**Comment by VincentBlase** [comment]
Je modifie ça
