### ISSUE TITLE
axe des ordonnées trop écrasé

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/ESI_viande_brousse#9]
essaye de passer à log(occurances/nbre de visite) en y pour voir si c'est pas mieux là les céphalophes et les athérures écrasent tout le reste

**Comment by VincentBlase** [comment]
La nouvelle version est en logarithme, c'est un peu moins écrasé du coup

**Comment by yannickkk** [comment]
je viens de regarder effectivement le log peut servir.
Cependant il faut faire comme pour weighted data une petite cas à cocher sont l'intitulé serait: "use logarythmic scale for y axis". On aura donc 4 cas:
données brutes sans échelle log
données brutes avec échelle log
données controlées par le nombre de visites sans échelle log
données controlées par le nombre de visites avec échelle log
